### PR TITLE
Updated Shell.py ps function to support Windows

### PR DESCRIPTION
**Pull request by jebeckford**

### CODE REVIEW

**Review by laszewsk — CHANGES_REQUESTED** [review]
from the internet

This command is no longer supplied with recent versions of the Windows resource kit, having been replaced by TASKLIST

deas tasklist provide the info we could use to identify the path.

i like to avoid an issue with installing another tool if possible

please discuss on slack

**Comment by laszewsk** [comment]
can we not just use tasklist \L

**Comment by jebeckford** [comment]
tasklist \L won't work but it's possible that what you and Praful were talking about on Slack will work using "wmic process where caption="python.exe" get commandline,processid".  If Praful is working on this I'll focus on something else though, let me know.

**Comment by laszewsk** [comment]
we only need one to focus on this

**Pull request closed without merging**
