### PR TITLE
modify ping method

### PR DESCRIPTION
**Pull request by hyspoc**
Tested pings method, the method does not work properly. I'm updating it to my newest version of ping. (function has been tested.)
please see lines 435-490. My text editor removed some empty spaces causing unnecessary line changes.

### CODE REVIEW

**Review by laszewsk — CHANGES_REQUESTED** [review]
could you please add a unit test for ping in cloudmes-common

maybe www.goole.com, and some other public ips would be cood to test the ping

i suggest the name

test_ping.py

**Comment by laszewsk** [comment]
also can you add the test to .travis.yaml this way we know automatically if it passes

**Comment by hyspoc** [comment]
also changed pings to class method.

**Review by laszewsk — CHANGES_REQUESTED** [review]
isnt script to be

script: 
   - pytest -v tests/test_tables.py
   - pytest -v tests/test_ping.py

**Review by laszewsk — COMMENTED** [review]
as i do not have write acesss in your repo i can not fix this. 
YOu can see if your test passes in the commit after a while

**Comment by laszewsk** [comment]
good that we do travis. it shows your ping method is not working 

how about adding the self.ping in the line 504 that travis reports

**Comment by laszewsk** [comment]
e;g; self.ping_ip

**Comment by hyspoc** [comment]
Sorry I don't know how to use travis. I forgot to delete the one of the redundant methods as I pushed that's what caused the error. Can you please check again?

**Comment by laszewsk** [comment]
ehy dont you check, There is a link in this pull request that says

Travis CI - Pull Request Failing after 28s — Build Failed .        Details

click on details than click on build and you gat a wonderful msg telling you whats wrong. Than you can fix this

**Comment by laszewsk** [comment]
for example you did not fix yet the missing self

**Comment by hyspoc** [comment]
ping_ips is not a inheritance method. there should not be self.ping_ips

**Comment by laszewsk** [comment]
great, but why is travis reporting an error o that line see the report on github. I described how to find it. if needed you can zoom

**Comment by hyspoc** [comment]
I've ran the test on my end multiple times, it always passes. Cloud it be because Travis uses python 2.7?

**Comment by laszewsk** [comment]
https://travis-ci.com/cloudmesh/cloudmesh-common/builds/109587114

**Comment by hyspoc** [comment]
Yes, I read the file. I am very inclined to think this is a python version issue.

**Comment by hyspoc** [comment]
The [documentation](https://docs.python.org/3.4/library/multiprocessing.html#multiprocessing.pool.Pool) says that multiprocessing.pool supports the context management protocol (with statements) in Python version 3.3 and above.

**Comment by laszewsk** [comment]
This is not a python version issue, but i think it is yoru pull request. If you vie wyour files in github you have committed the following and as you can see

a) you have outcommented ping_ip, so it does not exist.
b) you use ping_ip  instead of self.ping_ip as ping_ip is declared in the class it must be called with self.

so two reasons why travis correctly reports that your code is not yet perfect

#
    #     def ping_ip(self, ip, count=count):
    #         """
    #         ping a vm from given ip address
    #         :param ip: str of ip address
    #         :param timeout: given in seconds. if timeout expires, the process is killed
    #         :return: a str representing the ping result
    #         """
    #         param = '-n' if platform.system().lower() == 'windows' else '-c'
    #         command = ['ping', param, count, ip]
    #         ret_code = subprocess.run(command, capture_output=False).returncode
    #         return {ip: ret_code}
    #
    #     with Pool(processes=processors) as p:
    #         res = p.map(ping_ip, ips)
    #     return res

    @classmethod
    def pings(cls, ips=None, count=1, processors=3):
        """
        ping a list of given ip addresses
        :param ips: a list of ip addresses
        :param count: number of pings to run per ip
        :param processors: number of processors to Pool
        :return: list of dicts representing the ping result
        """
        # wrap ip and count into one list to be sent to Pool map
        args = [{'ip':ip, 'count':count} for ip in ips]

        with Pool(processors) as p:
            res = p.map(ping_ip, args)
        return res

    @classmethod
    def ping(cls, host=None, count=1):
        """
        execute ping
        :param host: the host to ping
        :param count: the number of pings
        :return:
        """
        option = '-n' if platform.system().lower() == 'windows' else '-c'
        return cls.execute('ping',
                           "{option} {count} {host}".format(option=option,
                                                            count=count,
                                                            host=host))

**Comment by hyspoc** [comment]
ping_ip is on line 141

**Comment by laszewsk** [comment]
I am sure you can add the self and get thsi working in travis

**Comment by laszewsk** [comment]
pleasae move the ping_ip into the class

**Comment by hyspoc** [comment]
As I commented on top of the ping_ip method. This is the only way to make ping a class method with Pool

**Comment by laszewsk** [comment]
Great. now i understand, you need it to be a function and not within a class, technicall you could do it difefrently, with cls, but keep as function, however it does not work ....

I will get somone else look at this

**Comment by laszewsk** [comment]
could you move your code to cloudmesh-cloud instead

put it in a dir 

cloudmesh.common3

thsi way we can be asured its not apython version issue as we assume cloudmesh  that seems easier than 

```
if sys.version_info[0] == 2:
    from contextlib import contextmanager
    @contextmanager
    def multiprocessing_context(*args, **kwargs):
        pool = multiprocessing.Pool(*args, **kwargs)
        yield pool
        pool.terminate()
else:
    multiprocessing_context = multiprocessing.Pool
```

**Comment by laszewsk** [comment]
I am now closing this pull request cloes move it to cloudmesh-cloud

**Pull request closed without merging**
